CREATE TABLE USERS
(
ID INT NOT NULL,
LastName VARCHAR(30) NOT NULL,
FirstName VARCHAR(30) NOT NULL,
BirthDate DATE NOT NULL,
Mail VARCHAR(80) NOT NULL,
Phone VARCHAR(30) NOT NULL,
MemberSince DATE NOT NULL,
Biography VARCHAR(255),
PhotoURL VARCHAR(255),
PRIMARY KEY (ID)
);
